#!/bin/csh
### test script for a serial job on one core with windfall on PBS

### Job Name
#PBS -N cokaPBSScript

### Email when job ends
#PBS -m bea
#PBS -M coka@email.arizona.edu

### PI Group for the job
#PBS -W group_list=ericlyons

### Queue for this job
#PBS -q windfall

### Jobtype for this job
#PBS -l jobtype=serial

### Cores and memory
#PBS -l select=1:ncpus=1:mem=1gb

### Share the node, otherwise you have all 12 cores
#PBS -l place=pack:shared

### Define the walltime required for this job
#PBS -l walltime=00:01:00

### Define the total cpu time required for this job
#PBS -l cput=00:01:00

### Load required modules/libraries if needed
source /usr/share/Modules/init/csh

### Set directory for job execution
cd ~coka/job1

### Run executable program with begin and end date and time output
date
/usr/bin/time echo "This is a test. Only a test. Do not panic."
date